config/routes.rb
Bennu::Application.routes.draw do

  match '/stickers/activate_index' => 'stickers#activate_index', :via => :get
  match '/stickers/activate/:id' => 'stickers#activate', :via => :get
  match '/stickers/import' => 'stickers#import', :via => :get
  match '/stickers/upload_import' => 'stickers#upload_import', :via => :post

  resources :stickers

  mount RailsAdmin::Engine => '/admin', :as => 'rails_admin'

  authenticated :user do
    root :to => 'home#index'
  end
  root :to => "home#index"
  devise_for :users
  resources :users


end

app/models/ability.rb
class Ability
  include CanCan::Ability

  def initialize(user)
    user ||= User.new # guest user (not logged in)
    if user.has_role? :admin
        can :manage, :all
        can :history
        can :access, :rails_admin   # grant access to rails_admin
        can :dashboard              # grant access to the dashboard
    else
        cannot :access, :rails_admin
        cannot :history
        cannot :dashboard        
    end
    # Define abilities for the passed in user here. For example:
    #
    #   user ||= User.new # guest user (not logged in)
    #   if user.admin?
    #     can :manage, :all
    #   else
    #     can :read, :all
    #   end
    #
    # The first argument to `can` is the action you are giving the user permission to do.
    # If you pass :manage it will apply to every action. Other common actions here are
    # :read, :create, :update and :destroy.
    #
    # The second argument is the resource the user can perform the action on. If you pass
    # :all it will apply to every resource. Otherwise pass a Ruby class of the resource.
    #
    # The third argument is an optional hash of conditions to further filter the objects.
    # For example, here the user can only update published articles.
    #
    #   can :update, Article, :published => true
    #
    # See the wiki for details: https://github.com/ryanb/cancan/wiki/Defining-Abilities
  end
end

app/models/message.rb
class Message < ActiveRecord::Base
  attr_accessible :confirm, :error, :name
end

app/models/role.rb
class Role < ActiveRecord::Base
  has_and_belongs_to_many :users, :join_table => :users_roles
  belongs_to :resource, :polymorphic => true
  
  scopify
end

app/models/sticker.rb
class Sticker < ActiveRecord::Base
  attr_accessible :message_id, :product_id, :code, :user_id, :production_date, :activated, :verified, :verifier
  belongs_to :user
  belongs_to :message

  validates :product_id, :code, :presence => true

  def self.can_import_from_csv?
    true
  end

end

app/models/user.rb
class User < ActiveRecord::Base
  rolify
  # Include default devise modules. Others available are:
  # :token_authenticatable, :confirmable,
  # :lockable, :timeoutable and :omniauthable
  devise :invitable, :database_authenticatable, :registerable, :confirmable,
         :recoverable, :rememberable, :trackable, :validatable

  # Setup accessible (or protected) attributes for your model
  attr_accessible :role_ids, :as => :admin
  attr_accessible :name, :email, :password, :password_confirmation, :remember_me
  
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery

  rescue_from CanCan::AccessDenied do |exception|
    redirect_to root_path, :alert => exception.message
  end

end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
    if !user_signed_in?
      redirect_to new_user_session_path
    else
        redirect_to stickers_path
    end
    @users = User.all
  end
end

app/controllers/stickers_controller.rb
class StickersController < ApplicationController
  # GET /stickers
  # GET /stickers.json
  def index
    @stickers = Sticker.all
    @activated = Sticker.where(:activated => 1)
    @verified = Sticker.where(:verified => 1)

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @stickers }
    end
  end

    def activate
    @sticker = Sticker.find(params[:id])

    respond_to do |format|
      if @sticker.update_attributes(:activated => 1)
        format.html { redirect_to "/stickers/activate_index", notice: 'Sticker was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @sticker.errors, status: :unprocessable_entity }
      end
    end
  end

  def activate_index
    @stickers = Sticker.all
    @activated = Sticker.where(:activated => 1)
    @verified = Sticker.where(:verified => 1)

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @stickers }
    end
  end


  # GET /stickers/1
  # GET /stickers/1.json
  def show
    @sticker = Sticker.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @sticker }
    end
  end

  # GET /stickers/new
  # GET /stickers/new.json
  def new
    @sticker = Sticker.new
    if current_user.has_role? :admin
      redirect_to "/admin/stickers/new"
    end
    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @sticker }
    end
  end

  # GET /stickers/1/edit
  def edit
    @sticker = Sticker.find(params[:id])
  end

  # POST /stickers
  # POST /stickers.json
  def create
    @sticker = Sticker.new(params[:sticker])

    respond_to do |format|
      if @sticker.save
        format.html { redirect_to @sticker, notice: 'Sticker was successfully created.' }
        format.json { render json: @sticker, status: :created, location: @sticker }
      else
        format.html { render action: "new" }
        format.json { render json: @sticker.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /stickers/1
  # PUT /stickers/1.json
  def update
    @sticker = Sticker.find(params[:id])

    respond_to do |format|
      if @sticker.update_attributes(params[:sticker])
        format.html { redirect_to @sticker, notice: 'Sticker was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @sticker.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /stickers/1
  # DELETE /stickers/1.json
  def destroy
    @sticker = Sticker.find(params[:id])
    @sticker.destroy

    respond_to do |format|
      format.html { redirect_to stickers_url }
      format.json { head :no_content }
    end
  end

  def import
    
  end

  def upload_import
    uploaded_io = params[:file] 
    filename = Rails.root.join('public', 'uploads', 'tmp', uploaded_io.original_filename)
    File.open(filename, 'wb') do |file|
      file.write(uploaded_io.read)
    end
    @log = []
    book = Spreadsheet.open filename
    sheet1 = book.worksheet 0
    i = -1
    sheet1.each do |row|
      i+=1
      attributes = { :product_id => row[0],
                     :code => row[1]
                   }
      begin
        Sticker.create!(attributes)
        @log << "Line #{i+1} - Successfully imported - Attributes: #{attributes.inspect}"
      rescue Exception => e
        @log << "Line #{i+1} - Error importing #{e.inspect} - Attributes: #{attributes.inspect}"
      end
    end
  end  


end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_filter :authenticate_user!

  def index
    authorize! :index, @user, :message => 'Not authorized as an administrator.'
    @users = User.all
  end

  def show
    @user = User.find(params[:id])
  end
  
  def update
    authorize! :update, @user, :message => 'Not authorized as an administrator.'
    @user = User.find(params[:id])
    if @user.update_attributes(params[:user], :as => :admin)
      redirect_to users_path, :notice => "User updated."
    else
      redirect_to users_path, :alert => "Unable to update user."
    end
  end
    
  def destroy
    authorize! :destroy, @user, :message => 'Not authorized as an administrator.'
    user = User.find(params[:id])
    unless user == current_user
      user.destroy
      redirect_to users_path, :notice => "User deleted."
    else
      redirect_to users_path, :notice => "Can't delete yourself."
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
  def display_base_errors resource
    return '' if (resource.errors.empty?) or (resource.errors[:base].empty?)
    messages = resource.errors[:base].map { |msg| content_tag(:p, msg) }.join
    html = <<-HTML
    <div class="alert alert-error alert-block">
      <button type="button" class="close" data-dismiss="alert">&#215;</button>
      #{messages}
    </div>
    HTML
    html.html_safe
  end  
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/stickers_helper.rb
module StickersHelper
end

app/views/home/index.html.haml
%h3 Home
- @users.each do |user|
  %p
    User: #{link_to user.name, user}

app/views/layouts/_messages.html.haml
- flash.each do |name, msg|
  - if msg.is_a?(String)
    %div{:class => "alert alert-#{name == :notice ? "success" : "error"}"}
      %a.close{"data-dismiss" => "alert"} ×
      = content_tag :div, msg, :id => "flash_#{name}"

app/views/layouts/_navigation.html.haml
= link_to "Bennu Value", root_path, :class => 'brand'
%ul.nav

  - if user_signed_in?


    - if current_user.has_role? :user
      %li
        = link_to 'Activate stickers', "/stickers/activate_index"

    - if current_user.has_role? :admin
      %li
        = link_to 'Manage stickers', stickers_path  # FIXME edit stickers (activate)

      %li
        = link_to 'Manage manufacturers', users_path

      %li
        = link_to 'Manage messages', "/admin/message"



  - else




%ul.nav.pull-right
  - if user_signed_in?
    %li
      = link_to current_user.name , edit_user_registration_path     
    %li
      = link_to 'Logout', destroy_user_session_path, :method=>'delete'
  - else
    %li
      = link_to 'Login', new_user_session_path
    %li
      = link_to 'Manufacturer registration', new_user_registration_path      

app/views/layouts/application.html.haml
!!!
%html
  %head
    %meta{:content => "width=device-width, initial-scale=1.0", :name => "viewport"}
      %title= content_for?(:title) ? yield(:title) : "Bennu"
      %meta{:content => content_for?(:description) ? yield(:description) : "Bennu", :name => "description"}
        = stylesheet_link_tag "application", :media => "all"
        = javascript_include_tag "application"
        = csrf_meta_tags
        = yield(:head)
  %body{:class => "#{controller_name} #{action_name}"}
    %header.navbar.navbar-fixed-top
      %nav.navbar-inner
        .container
          = render 'layouts/navigation'
    #main{:role => "main"}
      .container
        .content
          .row
            .span12
              = render 'layouts/messages'
              = yield
          %footer
      / ! end of .container
    / ! end of #main

app/views/stickers/_form.html.haml
= simple_form_for(@sticker) do |f|
  = f.error_notification

  .form-inputs

    = f.input :product_id
    = f.input :code
    = f.hidden_field :user_id, :value => current_user.id
    = f.input :production_date, :required => true
    = f.association :message, :required => true
    = f.hidden_field :activated, :value => 1

  .form-actions
    = f.button :submit

app/views/stickers/activate_index.html.haml
%h1 Stickers list for activation
%ul
  %li= "#{@stickers.count} stickers created"
  %li= "#{@activated.count} stickers activated"
  %li= "#{@verified.count} stickers verified"
%br
%p
  

.row
  .span12
    %table.table-striped.span10
      %tr
        %th.span2 product id
        %th.span2 code
        %th.span2 activated ?
        %th.span2 verified ?
        %th.span2 actions

      - @stickers.each do |sticker|
        %tr
          %td= sticker.product_id
          %td= sticker.code
          %td= sticker.activated ? "yes" : "no"
          %td= sticker.verified ? "yes" : "no"
          %td
            - if sticker.activated
              = link_to 'Desactivate', "/stickers/desactivate/#{sticker.id}", :class=> "btn btn-warning" 
            - else
              = link_to 'Activate', "/stickers/activate/#{sticker.id}", :class=> "btn btn-success" 

app/views/stickers/edit.html.haml
%h1 Editing sticker

= render 'form'

= link_to 'Show', @sticker
\|
= link_to 'Back', stickers_path

app/views/stickers/import.html.haml
%h1 Stickers Excel Import

= form_tag '/stickers/upload_import', :multipart => true, :method => :post do
  %p Select XLS file to import:
  = file_field_tag :file
  %p= submit_tag 'Upload'

  %p
    %a{:href => "/sticker_template.xls"} download file template

app/views/stickers/index.html.haml
%h1 Stickers list
%ul
  %li= "#{@stickers.count} stickers created"
  %li= "#{@activated.count} stickers activated"
  %li= "#{@verified.count} stickers verified"
%br
%p
  = link_to 'Import XLS Sticker', "/stickers/import", :class=> "btn"
%p
  = link_to 'Create New Sticker', "/admin/sticker/new", :class=> "btn"

.row
  .span12
    %table.table-striped.span10
      %tr
        %th.span2 product id
        %th.span2 code
        %th.span2 activated ?
        %th.span2 verified ?
        %th.span2 actions

      - @stickers.each do |sticker|
        %tr
          %td= sticker.product_id
          %td= sticker.code
          %td= sticker.activated ? "yes" : "no"
          %td= sticker.verified ? "yes" : "no"
          %td
            = link_to 'Show', sticker
            = " - "
            = link_to 'Edit', edit_sticker_path(sticker)
            = " - "
            = link_to 'Destroy', sticker, method: :delete, data: { confirm: 'Are you sure?' }

app/views/stickers/new.html.haml
%h1 Manufacturers cannot create new sticker

%p As a manufacturer, you cannot create new sticker
%p If the sticker or sticker range you have is not available, please ask admin to create new stickers id if you need so.

= link_to 'Back', stickers_path

app/views/stickers/show.html.haml
%p#notice= notice


= link_to 'Edit', edit_sticker_path(@sticker)
\|
= link_to 'Back', stickers_path

app/views/stickers/upload_import.html.haml
%h1 Sticker Excel Upload result

%p= link_to "Back", "/"

%ul
  - @log.each do |l|
    %li=l

  %li Done.

%p= link_to "Back", "/"

app/views/users/_user.html.haml
.modal{:id => "role-options-#{user.id}", :style => "display: none;"}
  = simple_form_for user, :url => user_path(user), :html => {:method => :put, :class => 'form-horizontal' } do |f|
    .modal-header
      %a.close{"data-dismiss" => "modal"} ×
      %h3 Change Role
    .modal-body
      = f.input :role_ids, :collection => Role.all, :as => :radio_buttons, :label_method => lambda {|t| t.name.titleize}, :label => false, :item_wrapper_class => 'inline'
    .modal-footer
      = f.submit "Change Role", :class => "btn"
      %a.btn{"data-dismiss" => "modal", :href => "#"} Close

app/views/users/index.html.haml
%h3 Users
.span8
  %table.table.table-condensed
    %thead
      %tr
        %th Username
        %th Email
        %th Registered
        %th Role
        %th
        %th
    %tbody
      - @users.each do |user|
        %tr
          %td= link_to user.name, user
          %td= user.email
          %td= user.created_at.to_date
          %td= user.roles.first.name.titleize unless user.roles.first.nil?
          %td
            %a.btn.btn-mini{"data-toggle" => "modal", :href => "#role-options-#{user.id}", :type => "button"} Change role
            = render user
          %td= link_to("Delete user", user_path(user), :data => { :confirm => "Are you sure?" }, :method => :delete, :class => 'btn btn-mini') unless user == current_user

  = link_to "Create new manufacturer", "/users/sign_up", :class => "btn btn-info"

app/views/users/show.html.haml
%h3 User
%p
  User: #{@user.name}
%p
  Email: #{@user.email if @user.email}